(quote "--SEMPTY")
SEMPTY

(quote "--SEMPTYP")
(SEMPTYP SEMPTY)
(SEMPTYP '())
(SEMPTYP '(a))
(SEMPTYP '(a b))
(SEMPTYP '(SEMPTY a))

(quote "--SMEMBERP")
(SMEMBERP 'a SEMPTY)
(SMEMBERP 'a '(a))
(SMEMBERP 'a '(a b))
(SMEMBERP 'b '(a b))
(SMEMBERP 'b '(a b c))

(quote "--SINCLUDE")
(SINCLUDE 'a SEMPTY)
(SINCLUDE 'b '(a))
(SINCLUDE 'c '(a b))
(SINCLUDE 'a '(a b c))
(SINCLUDE 'b '(a b c))
(SINCLUDE 'c '(a b c))

(quote "--SEXCLUDE")
(SEXCLUDE 'a SEMPTY)
(SEXCLUDE 'a '(a))
(SEXCLUDE 'b '(a b))
(SEXCLUDE 'b '(a b c))
(SEXCLUDE 'a '(b))
(SEXCLUDE 'a '(b c))

(quote "--sunion")
(sunion SEMPTY SEMPTY)
(sunion SEMPTY '(a))
(sunion '(a) SEMPTY)
(sunion '(a) '(a))
(sunion '(a) '(b))
(sunion '(a) '(b c))
(sunion '(b c) '(a))

(quote "--sintersection")
(sintersection SEMPTY SEMPTY)
(sintersection SEMPTY '(a))
(sintersection '(a) SEMPTY)
(sintersection '(a) '(a))
(sintersection '(a) '(b))
(sintersection '(a) '(a b))
(sintersection '(a b) '(a))
(sintersection '(a b) '(a b c))
(sintersection '(c b a) '(a b))

(quote "--sSDIFFERENCE")
(SDIFFERENCE SEMPTY SEMPTY)
(SDIFFERENCE SEMPTY '(a))
(SDIFFERENCE '(a) SEMPTY)
(SDIFFERENCE '(a) '(a))
(SDIFFERENCE '(a) '(b))
(SDIFFERENCE '(a) '(a b))
(SDIFFERENCE '(a b) '(a))
(SDIFFERENCE '(a b) '(a b c))
(SDIFFERENCE '(c b a) '(a b))

(quote "--SSYMMETRICDIFFERENCE")
(SSYMMETRICDIFFERENCE SEMPTY SEMPTY)
(SSYMMETRICDIFFERENCE SEMPTY '(a))
(SSYMMETRICDIFFERENCE '(a) SEMPTY)
(SSYMMETRICDIFFERENCE '(a) '(a))
(SSYMMETRICDIFFERENCE '(a) '(b))
(SSYMMETRICDIFFERENCE '(a) '(a b))
(SSYMMETRICDIFFERENCE '(a b) '(a))
(SSYMMETRICDIFFERENCE '(a b) '(a b c))
(SSYMMETRICDIFFERENCE '(c b a) '(a b))

(quote "--SSUBSETP")
(SSUBSETP SEMPTY SEMPTY)
(SSUBSETP SEMPTY '(a))
(SSUBSETP '(a) SEMPTY)
(SSUBSETP '(a) '(a))
(SSUBSETP '(a) '(b))
(SSUBSETP '(a) '(a b))
(SSUBSETP '(a b) '(a))
(SSUBSETP '(a b) '(a b c))
(SSUBSETP '(c b a) '(a b))

(quote "--SPROPERP")
(SPROPERP SEMPTY SEMPTY)
(SPROPERP SEMPTY '(a))
(SPROPERP '(a) SEMPTY)
(SPROPERP '(a) '(a))
(SPROPERP '(a) '(b))
(SPROPERP '(a) '(a b))
(SPROPERP '(a b) '(a))
(SPROPERP '(a b) '(a b c))
(SPROPERP '(c b a) '(a b))

(quote "--SEQUALP")
(SEQUALP SEMPTY SEMPTY)
(SEQUALP SEMPTY '(a))
(SEQUALP '(a) SEMPTY)
(SEQUALP '(a) '(a))
(SEQUALP '(a) '(b))
(SEQUALP '(a) '(a b))
(SEQUALP '(a b) '(a))
(SEQUALP '(a b) '(a b c))
(SEQUALP '(c b a) '(a b))
(SEQUALP '(c b a) '(a b c))
(SEQUALP '(c b a) '(a c b))




